Fix the C lowering for `RecordLift` to be compatible with C++.
C++ prohibits non-constant struct literal initializers from being implicitly
converted to narrower types, so insert explicit casts. This allows the
generated code to be compiled as both C and C++.

Specifically, this fixes the following error in C++:
```
test.c:40:5: error: non-constant-expression cannot be narrowed from type 'int32_t' (aka 'int') to 'enum_t' (aka 'unsigned char') in initializer list [-Wc++11-narrowing]
```

While debugging this, I also tidied up some redundant parens in `load_ext`.