fix: 'core' module conflict in Bindgen::emit (#568)
* fix: 'core' module conflict in Bindgen::emit

This commit is an attempt to avoid module name conflicts where a user
library may have a module defined as follows:
```rust
mod core;

wit_bindgen::generate!("component");
```
This would currently clash with the 'core' module used in the
`Bindgen::emit` function and result in a compilation error:
```console
31 | wit_bindgen::generate!("component");
     |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `mem` in `core`
```

Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

* squash! fix: 'core' module conflict in Bindgen::emit

This commit adds additional external crate prefixes (::) to 'core'
modules used in code generated from macros.

It also adds a "test" in that an empty module named 'core' has been
added to catch any future additions or modifications.

Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

---------

Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>